services:
  elasticsearch:
    image: elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - target: 9200
        host_ip: 127.0.0.1
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        host_ip: 127.0.0.1
        published: 9300
        protocol: tcp
        mode: host
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health?wait_for_status=green > /dev/null || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
    networks:
      - appinternal
  app:
    image: golang:bullseye
    tty: true
    entrypoint: /bin/bash
    init: true
    working_dir: /estype
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      TEMP_DIR: /test_tmp
    volumes:
      - type: bind
        source: "."
        target: "/estype"
      - type: volume
        source: test_tmp
        target: /estype_tmp
    networks:
      - appinternal
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  test_tmp: {}
networks:
  appinternal: {}
