// Code generated by github.com/ngicks/estype/generator/genestime/gen_builtin_layouts/gen.go. DO NOT EDIT.

// builtinlayouts is collection of date formats built in Elasticsearch
//
//go:generate go run ../../../generator/genestime/gen_builtin_layouts/gen.go -o layout.go
package builtinlayouts

import estime "github.com/ngicks/estype/fielddatatype/estime"

var BuiltinLayouts = map[string]estime.MultiLayout{
	"date_optional_time": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000Z0700",
		"06-1-2T15:04:05.000Z0700",
		"2006-01-02",
		"06-1-2",
	})),
	"strict_date_optional_time": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000Z0700",
		"2006-01-02",
	})),
	"strict_date_optional_time_nanos": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000000000Z0700",
		"2006-01-02",
	})),
	"basic_date": must(estime.NewMultiLayout([]string{
		"20060102",
		"060102",
	})),
	"basic_date_time": must(estime.NewMultiLayout([]string{
		"20060102T150405.000Z0700",
		"060102T150405.000Z0700",
	})),
	"basic_date_time_no_millis": must(estime.NewMultiLayout([]string{
		"20060102T150405Z0700",
		"060102T150405Z0700",
	})),
	"basic_ordinal_date": must(estime.NewMultiLayout([]string{
		"2006002",
		"06002",
	})),
	"basic_ordinal_date_time": must(estime.NewMultiLayout([]string{
		"2006002T150405.000Z0700",
		"06002T150405.000Z0700",
	})),
	"basic_ordinal_date_time_no_millis": must(estime.NewMultiLayout([]string{
		"2006002T150405Z0700",
		"06002T150405Z0700",
	})),
	"basic_time": must(estime.NewMultiLayout([]string{
		"150405.000Z0700",
	})),
	"basic_time_no_millis": must(estime.NewMultiLayout([]string{
		"150405Z0700",
	})),
	"basic_t_time": must(estime.NewMultiLayout([]string{
		"T150405.000Z0700",
	})),
	"basic_t_time_no_millis": must(estime.NewMultiLayout([]string{
		"T150405Z0700",
	})),
	"date": must(estime.NewMultiLayout([]string{
		"2006-01-02",
		"06-1-2",
	})),
	"strict_date": must(estime.NewMultiLayout([]string{
		"2006-01-02",
	})),
	"date_hour": must(estime.NewMultiLayout([]string{
		"2006-01-02T15",
		"06-1-2T15",
	})),
	"strict_date_hour": must(estime.NewMultiLayout([]string{
		"2006-01-02T15",
	})),
	"date_hour_minute": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04",
		"06-1-2T15:04",
	})),
	"strict_date_hour_minute": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04",
	})),
	"date_hour_minute_second": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05",
		"06-1-2T15:04:05",
	})),
	"strict_date_hour_minute_second": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05",
	})),
	"date_hour_minute_second_fraction": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000",
		"06-1-2T15:04:05.000",
	})),
	"strict_date_hour_minute_second_fraction": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000",
	})),
	"date_hour_minute_second_millis": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000",
		"06-1-2T15:04:05.000",
	})),
	"strict_date_hour_minute_second_millis": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000",
	})),
	"date_time": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000Z0700",
		"06-1-2T15:04:05.000Z0700",
	})),
	"strict_date_time": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05.000Z0700",
	})),
	"date_time_no_millis": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05Z0700",
		"06-1-2T15:04:05Z0700",
	})),
	"strict_date_time_no_millis": must(estime.NewMultiLayout([]string{
		"2006-01-02T15:04:05Z0700",
	})),
	"hour": must(estime.NewMultiLayout([]string{
		"15",
	})),
	"strict_hour": must(estime.NewMultiLayout([]string{
		"15",
	})),
	"hour_minute": must(estime.NewMultiLayout([]string{
		"15:04",
	})),
	"strict_hour_minute": must(estime.NewMultiLayout([]string{
		"15:04",
	})),
	"hour_minute_second": must(estime.NewMultiLayout([]string{
		"15:04:05",
	})),
	"strict_hour_minute_second": must(estime.NewMultiLayout([]string{
		"15:04:05",
	})),
	"hour_minute_second_fraction": must(estime.NewMultiLayout([]string{
		"15:04:05.000",
	})),
	"strict_hour_minute_second_fraction": must(estime.NewMultiLayout([]string{
		"15:04:05.000",
	})),
	"hour_minute_second_millis": must(estime.NewMultiLayout([]string{
		"15:04:05.000",
	})),
	"strict_hour_minute_second_millis": must(estime.NewMultiLayout([]string{
		"15:04:05.000",
	})),
	"ordinal_date": must(estime.NewMultiLayout([]string{
		"2006-002",
		"06-002",
	})),
	"strict_ordinal_date": must(estime.NewMultiLayout([]string{
		"2006-002",
	})),
	"ordinal_date_time": must(estime.NewMultiLayout([]string{
		"2006-002T15:04:05.000Z0700",
		"06-002T15:04:05.000Z0700",
	})),
	"strict_ordinal_date_time": must(estime.NewMultiLayout([]string{
		"2006-002T15:04:05.000Z0700",
	})),
	"ordinal_date_time_no_millis": must(estime.NewMultiLayout([]string{
		"2006-002T15:04:05Z0700",
		"06-002T15:04:05Z0700",
	})),
	"strict_ordinal_date_time_no_millis": must(estime.NewMultiLayout([]string{
		"2006-002T15:04:05Z0700",
	})),
	"time": must(estime.NewMultiLayout([]string{
		"15:04:05.000Z0700",
	})),
	"strict_time": must(estime.NewMultiLayout([]string{
		"15:04:05.000Z0700",
	})),
	"time_no_millis": must(estime.NewMultiLayout([]string{
		"15:04:05Z0700",
	})),
	"strict_time_no_millis": must(estime.NewMultiLayout([]string{
		"15:04:05Z0700",
	})),
	"t_time": must(estime.NewMultiLayout([]string{
		"T15:04:05.000Z0700",
	})),
	"strict_t_time": must(estime.NewMultiLayout([]string{
		"T15:04:05.000Z0700",
	})),
	"t_time_no_millis": must(estime.NewMultiLayout([]string{
		"T15:04:05Z0700",
	})),
	"strict_t_time_no_millis": must(estime.NewMultiLayout([]string{
		"T15:04:05Z0700",
	})),
	"year": must(estime.NewMultiLayout([]string{
		"2006",
		"06",
	})),
	"strict_year": must(estime.NewMultiLayout([]string{
		"2006",
	})),
	"year_month": must(estime.NewMultiLayout([]string{
		"2006-01",
		"06-1",
	})),
	"strict_year_month": must(estime.NewMultiLayout([]string{
		"2006-01",
	})),
	"year_month_day": must(estime.NewMultiLayout([]string{
		"2006-01-02",
		"06-1-2",
	})),
	"strict_year_month_day": must(estime.NewMultiLayout([]string{
		"2006-01-02",
	}))}
