// Code generated by github.com/ngicks/estype/generator/gen_aggregate_metric_double/gen.go. DO NOT EDIT.

package fielddatatype

// AggregateMetricDoubleMin represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMin struct {
	Min float64 `json:"min"`
}

// AggregateMetricDoubleMax represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMax struct {
	Max float64 `json:"max"`
}

// AggregateMetricDoubleMinMax represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinMax struct {
	Min float64 `json:"min"`
	Max float64 `json:"max"`
}

// AggregateMetricDoubleSum represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleSum struct {
	Sum float64 `json:"sum"`
}

// AggregateMetricDoubleMinSum represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinSum struct {
	Min float64 `json:"min"`
	Sum float64 `json:"sum"`
}

// AggregateMetricDoubleMaxSum represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMaxSum struct {
	Max float64 `json:"max"`
	Sum float64 `json:"sum"`
}

// AggregateMetricDoubleMinMaxSum represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinMaxSum struct {
	Min float64 `json:"min"`
	Max float64 `json:"max"`
	Sum float64 `json:"sum"`
}

// AggregateMetricDoubleValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleValueCount struct {
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleMinValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinValueCount struct {
	Min        float64 `json:"min"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleMaxValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMaxValueCount struct {
	Max        float64 `json:"max"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleMinMaxValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinMaxValueCount struct {
	Min        float64 `json:"min"`
	Max        float64 `json:"max"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleSumValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleSumValueCount struct {
	Sum        float64 `json:"sum"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleMinSumValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMinSumValueCount struct {
	Min        float64 `json:"min"`
	Sum        float64 `json:"sum"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDoubleMaxSumValueCount represents Aggregate metric field type.
// As suffix suggests it is a partial object whose fields are explicitly enabled in mapping.json.
type AggregateMetricDoubleMaxSumValueCount struct {
	Max        float64 `json:"max"`
	Sum        float64 `json:"sum"`
	ValueCount float64 `json:"value_count"`
}

// AggregateMetricDouble represents Aggregated metric field type.
// Every fields were explicitly enabled in mapping.json
type AggregateMetricDouble struct {
	Min        float64 `json:"min"`
	Max        float64 `json:"max"`
	Sum        float64 `json:"sum"`
	ValueCount float64 `json:"value_count"`
}
